# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
# - deployment.yaml
# - services.yaml

# namespace: goapp

# images:
# - name: pandudw/goserver-img
#   newName: pandudw/goserver-img
#   newTag: v2
