name: goserver_actions_argocd
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: 'actions/checkout@v2'
      - name: build image 
        uses: docker/build-push-action@v1
        with:
          username: pandudw
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pandudw/goserver_github-actions_argocd
          tag: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1
      
      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image goserver-img=pandudw/goserver_github-actions_argocd:${{ github.sha }}
          cat kustomization.yaml

      - name: push
        uses: ad-m/github-push-action@master